kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: bifoql
  namespace: default
  labels:
    app: bifoql
    role: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bifoql
      role: web
  template:
    metadata:
      name: bifoql
      labels:
        app: bifoql
        role: web
    spec:
      containers:
      - name: bifoql
        image: 779051441487.dkr.ecr.eu-west-1.amazonaws.com/bifoql:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bifoql
  labels:
    app: bifoql
    role: web
    dns: route53
  annotations:
    domainName: bifoql
    # All of these aws-load-balancer annotations are required to do HTTPS->HTTP ELB SSL termination
    # See https://github.com/kubernetes/kubernetes/issues/36845#issuecomment-267491260
    # SSL cert for *.clusters.storefront.vpsvc.com
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:779051441487:certificate/33a11b9f-ef86-4dd1-bef9-2674b9bbc7c9"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  selector:
    app: bifoql
    role: web
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 80 # SSL termination, forward to target HTTP port
  type: LoadBalancer
